:-module(keywords, [keyword/1,isKeyword/1]).

  isKeyword(X):- keyword(X), !.

  keyword("|").
  keyword("||").
  keyword(";").
  keyword(":").
  keyword("::").
  keyword(",").
  keyword("..").
  keyword("?").
  keyword("!").
  keyword("^").
  keyword("^^").
  keyword("~").
  keyword("=").
  keyword("==").
  keyword(".=").
  keyword(":=").
  keyword("=>").
  keyword("->").
  keyword(":-").
  keyword(":--").
  keyword("-->").
  keyword("::=").
  keyword("<=").
  keyword("<~").
  keyword("-").
  keyword("*").
  keyword("/").
  keyword("+").
  keyword("$").
  keyword("*>").
  keyword("\\+").
  keyword("\\=").
  keyword("!=").
  keyword(".").
  keyword("%").
  keyword("%%").
  keyword("@").
  keyword("@@").
  keyword("in").
  keyword("case").
  keyword("valof").
  keyword("valis").
  keyword("istrue").
  keyword("true").
  keyword("false").
  keyword("fail").
  keyword("action").
  keyword("spawn").
  keyword("onerror").
  keyword("sync").
  keyword("raise").
  keyword("timeout").
  keyword("import").
  keyword("opaque").
  keyword("$meta").
  keyword("#").